### ISSUE TITLE
Fail to compile

### ISSUE THREAD

**Issue by bigbruno** [calum74/s2#2]
Hi, i'm trying in debian stable or testing, but show same error:

/home/bruno/spookys2/s2/src/Control.cpp: In member function ‘virtual void Controller::Waveform(S2::BuiltinWaveform)’:
/home/bruno/spookys2/s2/src/Control.cpp:51:26: error: ‘virtual void S2::Channel::Waveform(S2::BuiltinWaveform)’ is private within this context
   GetChannel().Waveform(f);
                          ^
In file included from /home/bruno/spookys2/s2/src/S2.h:10:0,
                 from /home/bruno/spookys2/s2/src/Control.cpp:1:
/home/bruno/spookys2/s2/src/Generator.h:30:16: note: declared private here
   virtual void Waveform(BuiltinWaveform value) = 0;
                ^~~~~~~~
/home/bruno/spookys2/s2/src/Control.cpp: In member function ‘virtual void Controller::Waveform(const int (&)[1024])’:
/home/bruno/spookys2/s2/src/Control.cpp:57:29: error: ‘virtual void S2::Channel::Waveform(const int (&)[1024])’ is private within this context
   GetChannel().Waveform(data);
                             ^
In file included from /home/bruno/spookys2/s2/src/S2.h:10:0,
                 from /home/bruno/spookys2/s2/src/Control.cpp:1:
/home/bruno/spookys2/s2/src/Generator.h:31:16: note: declared private here
   virtual void Waveform(const WaveData & data)=0;
                ^~~~~~~~
/home/bruno/spookys2/s2/src/Control.cpp: In member function ‘virtual void Controller::Amplitude(double)’:
/home/bruno/spookys2/s2/src/Control.cpp:63:27: error: ‘virtual void S2::Channel::Amplitude(double)’ is private within this context
   GetChannel().Amplitude(a);
                           ^
In file included from /home/bruno/spookys2/s2/src/S2.h:10:0,
                 from /home/bruno/spookys2/s2/src/Control.cpp:1:
/home/bruno/spookys2/s2/src/Generator.h:28:16: note: declared private here
   virtual void Amplitude(double value) = 0;
                ^~~~~~~~~
/home/bruno/spookys2/s2/src/Control.cpp: In member function ‘virtual void Controller::Frequency(double)’:
/home/bruno/spookys2/s2/src/Control.cpp:69:27: error: ‘virtual void S2::Channel::Frequency(double)’ is private within this context
   GetChannel().Frequency(f);
                           ^
In file included from /home/bruno/spookys2/s2/src/S2.h:10:0,
                 from /home/bruno/spookys2/s2/src/Control.cpp:1:
/home/bruno/spookys2/s2/src/Generator.h:29:16: note: declared private here
   virtual void Frequency(double value) = 0;
                ^~~~~~~~~
/home/bruno/spookys2/s2/src/Control.cpp: In member function ‘virtual void Controller::Output(bool)’:
/home/bruno/spookys2/s2/src/Control.cpp:75:24: error: ‘virtual void S2::Channel::Output(bool)’ is private within this context
   GetChannel().Output(b);
                        ^
In file included from /home/bruno/spookys2/s2/src/S2.h:10:0,
                 from /home/bruno/spookys2/s2/src/Control.cpp:1:
/home/bruno/spookys2/s2/src/Generator.h:33:16: note: declared private here
   virtual void Output(bool b) = 0;
                ^~~~~~
/home/bruno/spookys2/s2/src/Control.cpp: In member function ‘virtual void Controller::Offset(double)’:
/home/bruno/spookys2/s2/src/Control.cpp:96:24: error: ‘virtual void S2::Channel::Offset(double)’ is private within this context
   GetChannel().Offset(p);
                        ^
In file included from /home/bruno/spookys2/s2/src/S2.h:10:0,
                 from /home/bruno/spookys2/s2/src/Control.cpp:1:
/home/bruno/spookys2/s2/src/Generator.h:34:16: note: declared private here
   virtual void Offset(double p) = 0;
                ^~~~~~
/home/bruno/spookys2/s2/src/Control.cpp: In member function ‘virtual void Controller::Duty(double)’:
/home/bruno/spookys2/s2/src/Control.cpp:114:25: error: ‘virtual void S2::Channel::Duty(double)’ is private within this context
   GetChannel().Duty(duty);
                         ^
In file included from /home/bruno/spookys2/s2/src/S2.h:10:0,
                 from /home/bruno/spookys2/s2/src/Control.cpp:1:
/home/bruno/spookys2/s2/src/Generator.h:32:16: note: declared private here
   virtual void Duty(double p) = 0;
                ^~~~
CMakeFiles/s2core.dir/build.make:62: recipe for target 'CMakeFiles/s2core.dir/src/Control.cpp.o' failed
make[2]: *** [CMakeFiles/s2core.dir/src/Control.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/s2core.dir/all' failed
make[1]: *** [CMakeFiles/s2core.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by DiamondGeezer** [comment]
Hey Bruno. Were you able to get this to build? I'm receiving the same build errors.

**Comment by vstepaniuk** [comment]
@calum74 Same on Ubuntu 20.04. Could you please have a look at this?

**Comment by bigbruno** [comment]
Today i'm tried again and make little changes to compile in BigLinux/Ubuntu 20.04, not work all functions, but work, see fork: https://github.com/biglinux/s2

**Comment by vstepaniuk** [comment]
@bigbruno thanks! it works

**Comment by xandark** [comment]
There have been updates to the code recently. Does this issue still apply?
